### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by Henning-K** [Henning-K/cargo-authors#2]
This is intended as a roadmap of sorts for features that are likely to be implemented in the future.

First should probably be to provide an option to make the output machine-readable, I'm thinking Json for this.

----

- [x] Machine-readable output with Json
- [x] Output: --by-crate
- [x] Output: --hide-emails
- [x] Output: --hide-authors
- [x] Output: --hide-crates
- [x] path argument => no dependence on current working directory
. . .

----

Suggestions for additional future features are welcome.
